<a href="https://colab.research.google.com/github/Dennisogaka/Explanatory-Data-Analysis/blob/main/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
crops = pd.read_csv("crops.csv") # importing the file
crops.head() # the first five rows
crops.tail() # the last five rows
crops.info() # the table information on all columns (null & non-null values)
crops.describe() # the statistical description of the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Farmer Name               500 non-null    object
 1   County                    460 non-null    object
 2   Crop Type                 463 non-null    object
 3   Crop Variety              469 non-null    object
 4   Season                    470 non-null    object
 5   Planted Area (Acres)      489 non-null    object
 6   Yield (Kg)                482 non-null    object
 7   Market Price (KES/Kg)     483 non-null    object
 8   Revenue (KES)             429 non-null    float64
 9   Cost of Production (KES)  481 non-null    object
 10  Profit (KES)              404 non-null    float64
 11  Planting Date             483 non-null    object
 12  Harvest Date              490 non-null    object
 13  Soil Type                 471 non-null    object
 14  Irrigation Method         349 non-null    object
 15  Fertilizer Used           367 non-null    object
 16  Pest Control              319 non-null    object
 17  Weather Impact            315 non-null    object
 18  Farmer Contact            484 non-null    object
 19  Notes                     301 non-null    object
dtypes: float64(2), object(18)
memory usage: 78.3+ KB

       Revenue (KES)  Profit (KES)
count   4.290000e+02  4.040000e+02
mean    2.778182e+06  2.714988e+06
std     2.828982e+06  2.781303e+06
min     1.371635e+04 -3.893797e+04
25%     6.945902e+05  5.697680e+05
50%     1.705241e+06  1.660569e+06
75%     4.214462e+06  4.221648e+06
max     1.327797e+07  1.322674e+07

In [3]:
crops.columns #the columns we have in our dataset
crops.shape # the total number of rows vs columns

(500, 20)

In [4]:
crops.isnull().sum() # total null values in every column

Farmer Name                   0
County                       40
Crop Type                    37
Crop Variety                 31
Season                       30
Planted Area (Acres)         11
Yield (Kg)                   18
Market Price (KES/Kg)        17
Revenue (KES)                71
Cost of Production (KES)     19
Profit (KES)                 96
Planting Date                17
Harvest Date                 10
Soil Type                    29
Irrigation Method           151
Fertilizer Used             133
Pest Control                181
Weather Impact              185
Farmer Contact               16
Notes                       199
dtype: int64

In [5]:
crops.nunique() #identifies number of unique values per column

Farmer Name                 500
County                       11
Crop Type                    11
Crop Variety                  4
Season                        4
Planted Area (Acres)        427
Yield (Kg)                  474
Market Price (KES/Kg)       460
Revenue (KES)               429
Cost of Production (KES)    470
Profit (KES)                404
Planting Date               269
Harvest Date                265
Soil Type                     6
Irrigation Method             4
Fertilizer Used               5
Pest Control                  3
Weather Impact                3
Farmer Contact              311
Notes                         4
dtype: int64

In [6]:
crops.duplicated().sum() # determines existing duplicates in a dataset

np.int64(0)

In [7]:
(crops[crops["County"]=="Nairobi"]).head()

,Farmer Name,County,Crop Type,Crop Variety,Season,Planted Area (Acres),Yield (Kg),Market Price (KES/Kg),Revenue (KES),Cost of Production (KES),Profit (KES),Planting Date,Harvest Date,Soil Type,Irrigation Method,Fertilizer Used,Pest Control,Weather Impact,Farmer Contact,Notes
8,Farmer 9,Nairobi,Cassava,Hybrid,Short Rains,11.03,4757.72,27.42,1438937.21,21508.58,1417428.63,2023-03-31,2023-04-14,Sandy,Sprinkler,DAP,Organic,Mild,0730863865,High yield
14,Farmer 15,Nairobi,Maize,Hybrid,Dry Season,1.72,2625.34,113.38,511977.00,55055.36,456921.64,2023-09-03,2023-06-09,NaN,NaN,NaN,Chemical,Severe,0784158663,Pest issues
43,Farmer 44,Nairobi,Coffee,Local,Short Rains,1.96,4944.46,60.98,590965.81,39185.83,551779.98,2023-10-30,2024-01-17,Loam,Flood,UREA,Chemical,Mild,0755667651,Pest issues
47,Farmer 48,Nairobi,Tea,NaN,Dry Season,6.7,2761.09,184.54,3413861.38,29000.07,3384861.31,2023-10-03,2024-02-15,Error,Sprinkler,Manure,Organic,Severe,0724366125,NaN
64,Farmer 65,Nairobi,Coffee,Local,Short Rains,11.38,2553.22,43.99,1278157.76,NaN,NaN,2023-10-17,2023-06-16,Loam,Drip,CAN,Chemical,NaN,0747308985,NaN

In [8]:
crops[(crops["County"]=="Nairobi") & (crops["Crop Type"]=="Tea")].head()

,Farmer Name,County,Crop Type,Crop Variety,Season,Planted Area (Acres),Yield (Kg),Market Price (KES/Kg),Revenue (KES),Cost of Production (KES),Profit (KES),Planting Date,Harvest Date,Soil Type,Irrigation Method,Fertilizer Used,Pest Control,Weather Impact,Farmer Contact,Notes
47,Farmer 48,Nairobi,Tea,NaN,Dry Season,6.7,2761.09,184.54,3413861.38,29000.07,3384861.31,2023-10-03,2024-02-15,Error,Sprinkler,Manure,Organic,Severe,0724366125,NaN
213,Farmer 214,Nairobi,Tea,NaN,Dry Season,2.55,Error,111.51,NaN,65188.69,NaN,2023-11-09,2024-02-17,NaN,NaN,NaN,Organic,Mild,0713704481,NaN
294,Farmer 295,Nairobi,Tea,Local,Long Rains,7.22,4761.61,80.71,2774714.90,NaN,NaN,2023-01-26,2024-03-03,Silty,Drip,CAN,NaN,NaN,0799038526,NaN
308,Farmer 309,Nairobi,Tea,Local,Short Rains,3.84,3225.04,NaN,NaN,56224.81,NaN,2023-10-09,2023-08-13,Silty,Drip,DAP,Chemical,NaN,0771510041,NaN
433,Farmer 434,Nairobi,Tea,Hybrid,Dry Season,Error,4886.09,71.07,NaN,77084.87,NaN,2023-08-29,2023-11-27,NaN,Drip,NaN,NaN,NaN,0766775103,Delayed harvest

In [9]:
crops[(crops["County"]=="Nairobi") & (crops["Crop Type"]=="Tea")].tail()

,Farmer Name,County,Crop Type,Crop Variety,Season,Planted Area (Acres),Yield (Kg),Market Price (KES/Kg),Revenue (KES),Cost of Production (KES),Profit (KES),Planting Date,Harvest Date,Soil Type,Irrigation Method,Fertilizer Used,Pest Control,Weather Impact,Farmer Contact,Notes
213,Farmer 214,Nairobi,Tea,NaN,Dry Season,2.55,Error,111.51,NaN,65188.69,NaN,2023-11-09,2024-02-17,NaN,NaN,NaN,Organic,Mild,0713704481,NaN
294,Farmer 295,Nairobi,Tea,Local,Long Rains,7.22,4761.61,80.71,2774714.90,NaN,NaN,2023-01-26,2024-03-03,Silty,Drip,CAN,NaN,NaN,0799038526,NaN
308,Farmer 309,Nairobi,Tea,Local,Short Rains,3.84,3225.04,NaN,NaN,56224.81,NaN,2023-10-09,2023-08-13,Silty,Drip,DAP,Chemical,NaN,0771510041,NaN
433,Farmer 434,Nairobi,Tea,Hybrid,Dry Season,Error,4886.09,71.07,NaN,77084.87,NaN,2023-08-29,2023-11-27,NaN,Drip,NaN,NaN,NaN,0766775103,Delayed harvest
456,Farmer 457,Nairobi,Tea,Hybrid,Dry Season,14.36,2245.98,112.04,3613544.64,32589.43,3580955.21,2023-10-03,2024-03-17,Error,Flood,DAP,NaN,Mild,0730005727,Pest issues

In [10]:
crops[(crops["County"]=="Nairobi") & (crops["Crop Type"]=="Tea")]

,Farmer Name,County,Crop Type,Crop Variety,Season,Planted Area (Acres),Yield (Kg),Market Price (KES/Kg),Revenue (KES),Cost of Production (KES),Profit (KES),Planting Date,Harvest Date,Soil Type,Irrigation Method,Fertilizer Used,Pest Control,Weather Impact,Farmer Contact,Notes
47,Farmer 48,Nairobi,Tea,NaN,Dry Season,6.7,2761.09,184.54,3413861.38,29000.07,3384861.31,2023-10-03,2024-02-15,Error,Sprinkler,Manure,Organic,Severe,0724366125,NaN
213,Farmer 214,Nairobi,Tea,NaN,Dry Season,2.55,Error,111.51,NaN,65188.69,NaN,2023-11-09,2024-02-17,NaN,NaN,NaN,Organic,Mild,0713704481,NaN
294,Farmer 295,Nairobi,Tea,Local,Long Rains,7.22,4761.61,80.71,2774714.90,NaN,NaN,2023-01-26,2024-03-03,Silty,Drip,CAN,NaN,NaN,0799038526,NaN
308,Farmer 309,Nairobi,Tea,Local,Short Rains,3.84,3225.04,NaN,NaN,56224.81,NaN,2023-10-09,2023-08-13,Silty,Drip,DAP,Chemical,NaN,0771510041,NaN
433,Farmer 434,Nairobi,Tea,Hybrid,Dry Season,Error,4886.09,71.07,NaN,77084.87,NaN,2023-08-29,2023-11-27,NaN,Drip,NaN,NaN,NaN,0766775103,Delayed harvest
456,Farmer 457,Nairobi,Tea,Hybrid,Dry Season,14.36,2245.98,112.04,3613544.64,32589.43,3580955.21,2023-10-03,2024-03-17,Error,Flood,DAP,NaN,Mild,0730005727,Pest issues

In [11]:
crops[(crops["County"]=="Nairobi") & (crops["Crop Type"]=="Tea")].describe()

       Revenue (KES)  Profit (KES)
count   3.000000e+00  2.000000e+00
mean    3.267374e+06  3.482908e+06
std     4.381813e+05  1.386593e+05
min     2.774715e+06  3.384861e+06
25%     3.094288e+06  3.433885e+06
50%     3.413861e+06  3.482908e+06
75%     3.513703e+06  3.531932e+06
max     3.613545e+06  3.580955e+06

In [12]:
crops.sort_values(['County', 'Crop Type'], ascending=(True, True))

,Farmer Name,County,Crop Type,Crop Variety,Season,Planted Area (Acres),Yield (Kg),Market Price (KES/Kg),Revenue (KES),Cost of Production (KES),Profit (KES),Planting Date,Harvest Date,Soil Type,Irrigation Method,Fertilizer Used,Pest Control,Weather Impact,Farmer Contact,Notes
60,Farmer 61,Eldoret,Beans,NaN,Dry Season,18.9,1898.71,118.12,4238809.32,87108.86,4151700.46,2023-11-21,2023-10-13,Error,Error,CAN,Organic,Severe,0760119651,NaN
128,Farmer 129,Eldoret,Beans,Error,Error,6.33,3108.62,62.0,1220009.01,47237.33,1172771.68,2023-10-28,2023-07-15,Silty,NaN,CAN,NaN,Mild,0748285503,NaN
174,Farmer 175,Eldoret,Beans,Local,Long Rains,14.72,2316.37,61.93,2111625.13,49181.81,2062443.32,2023-11-18,2024-03-12,NaN,NaN,DAP,Organic,Mild,0796977837,Pest issues
178,Farmer 179,Eldoret,Beans,Local,Short Rains,19.02,2414.21,21.35,980355.15,31750.58,948604.57,2023-03-08,2023-09-22,Loam,NaN,NaN,Organic,Mild,0747463522,Pest issues
188,Farmer 189,Eldoret,Beans,Local,Long Rains,0.56,1401.94,62.7,49224.92,34422.98,14801.94,2023-07-01,2023-06-17,Error,Sprinkler,Manure,NaN,NaN,0724366125,Pest issues
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,Farmer 69,NaN,NaN,Organic,Dry Season,18.49,1196.59,44.84,992082.72,30909.69,961173.03,2023-11-14,2023-06-21,Silty,NaN,NaN,Chemical,Mild,0739436733,NaN
383,Farmer 384,NaN,NaN,Local,Short Rains,8.23,4757.86,81.93,3208148.40,75595.86,3132552.54,2023-01-19,2023-05-23,Clay,NaN,DAP,Organic,NaN,0770897765,Pest issues
423,Farmer 424,NaN,NaN,Hybrid,Short Rains,Error,3894.66,167.44,NaN,55091.82,NaN,2023-11-13,2023-08-27,Silty,NaN,UREA,Organic,Severe,0727758595,High yield
446,Farmer 447,NaN,NaN,Local,Dry Season,1.47,2374.31,NaN,NaN,93441.34,NaN,NaN,2023-11-04,Sandy,NaN,UREA,Organic,Severe,0784437458,NaN
484,Farmer 485,NaN,NaN,Hybrid,Long Rains,18.6,3062.1,186.97,10648887.57,74246.89,10574640.68,2023-06-15,2024-03-23,Silty,Sprinkler,DAP,Chemical,Mild,0773993471,Delayed harvest

In [13]:
crops.sort_values(['County'], ascending=(True))

,Farmer Name,County,Crop Type,Crop Variety,Season,Planted Area (Acres),Yield (Kg),Market Price (KES/Kg),Revenue (KES),Cost of Production (KES),Profit (KES),Planting Date,Harvest Date,Soil Type,Irrigation Method,Fertilizer Used,Pest Control,Weather Impact,Farmer Contact,Notes
67,Farmer 68,Eldoret,Sorghum,Local,Long Rains,3.5,1703.96,26.54,158280.84,16592.11,141688.73,2023-04-16,2024-01-07,Loam,Flood,UREA,Error,Severe,0761019678,Error
35,Farmer 36,Eldoret,Error,Organic,Short Rains,12.53,4006.27,123.45,6197012.61,97424.01,6099588.60,2023-07-18,2023-06-28,Peaty,Flood,DAP,Chemical,Severe,0791363974,High yield
115,Farmer 116,Eldoret,Sorghum,Organic,Long Rains,4.96,4814.62,12.64,301849.71,96500.09,205349.62,2023-03-31,2023-06-08,Clay,NaN,DAP,NaN,Severe,0713326769,Pest issues
38,Farmer 39,Eldoret,NaN,Hybrid,Dry Season,19.43,2898.98,194.71,10967465.49,56080.06,10911385.43,2023-01-07,2024-02-14,Silty,Sprinkler,NaN,Organic,Severe,0795511909,NaN
418,Farmer 419,Eldoret,Tea,Local,Long Rains,6.14,3960.59,151.15,3675669.12,21283.89,3654385.23,2023-10-25,2024-02-03,Error,NaN,DAP,Organic,Severe,0750056581,High yield
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461,Farmer 462,NaN,Tomatoes,Hybrid,Dry Season,7.62,784.6,52.29,312623.71,11311.13,301312.58,2023-04-29,2024-03-20,Sandy,Flood,UREA,NaN,Severe,0794705205,High yield
465,Farmer 466,NaN,Rice,Local,Dry Season,5.56,3392.88,94.84,1789100.91,46315.29,1742785.62,2023-03-23,2023-07-18,Clay,Flood,NaN,Organic,Mild,0724549543,NaN
484,Farmer 485,NaN,NaN,Hybrid,Long Rains,18.6,3062.1,186.97,10648887.57,74246.89,10574640.68,2023-06-15,2024-03-23,Silty,Sprinkler,DAP,Chemical,Mild,0773993471,Delayed harvest
487,Farmer 488,NaN,Tea,NaN,Long Rains,10.17,4776.8,Error,NaN,90941.99,NaN,2023-08-23,2023-11-19,Silty,NaN,CAN,Chemical,NaN,0735921441,NaN
497,Farmer 498,NaN,Beans,Organic,Dry Season,0.67,2133.31,155.02,221572.83,2280.99,219291.84,2023-11-26,2024-01-31,Loam,Flood,Manure,NaN,Mild,0718526544,NaN

In [14]:
crops.rename({'Crop Variety': 'COP','Market Price':'MP' }, axis=1, inplace=True)
crops

,Farmer Name,County,Crop Type,COP,Season,Planted Area (Acres),Yield (Kg),Market Price (KES/Kg),Revenue (KES),Cost of Production (KES),Profit (KES),Planting Date,Harvest Date,Soil Type,Irrigation Method,Fertilizer Used,Pest Control,Weather Impact,Farmer Contact,Notes
0,Farmer 1,Kiambu,Potatoes,Organic,Long Rains,15.14,1654.76,100.19,2510066.72,8977.19,2501089.53,2023-08-01,2023-11-02,Peaty,Drip,NaN,Organic,Mild,0731810617,High yield
1,Farmer 2,Meru,Coffee,Local,Short Rains,13.54,1957.61,168.63,4469713.42,47882.55,4421830.87,2023-02-25,2023-09-07,Silty,Sprinkler,Error,Organic,Mild,0773993471,NaN
2,Farmer 3,Nakuru,Sorghum,Error,Long Rains,19.33,4679.65,102.63,9283667.03,69370.32,9214296.71,2023-07-08,2023-12-28,Peaty,NaN,CAN,NaN,NaN,0778642041,Delayed harvest
3,Farmer 4,Eldoret,Potatoes,Organic,Short Rains,1.56,420.18,125.2,82066.20,43454.15,38612.05,2023-03-22,2024-01-08,NaN,NaN,UREA,Chemical,Mild,0758586340,NaN
4,Farmer 5,Machakos,Tomatoes,Hybrid,Short Rains,13.93,Error,199.42,NaN,69673.69,NaN,2023-03-01,2023-10-24,Clay,NaN,UREA,NaN,Severe,0770291817,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Farmer 496,Eldoret,Potatoes,Hybrid,Dry Season,10.06,2023.1,50.35,1024742.64,27940.08,996802.56,2023-11-08,2023-04-07,NaN,Drip,DAP,NaN,Mild,0779008866,Delayed harvest
496,Farmer 497,Eldoret,Beans,Hybrid,Dry Season,19.4,3223.27,95.21,5953618.21,68258.75,5885359.46,2023-09-26,2023-09-11,Clay,Flood,NaN,Chemical,Severe,0768353204,Delayed harvest
497,Farmer 498,NaN,Beans,Organic,Dry Season,0.67,2133.31,155.02,221572.83,2280.99,219291.84,2023-11-26,2024-01-31,Loam,Flood,Manure,NaN,Mild,0718526544,NaN
498,Farmer 499,Kericho,Cassava,Hybrid,Dry Season,6.36,4112.78,Error,NaN,54915.02,NaN,2023-11-17,2023-09-24,Loam,Sprinkler,NaN,Chemical,Mild,0725014631,Pest issues
499,Farmer 500,Meru,Tea,Organic,Dry Season,10.74,Error,174.88,NaN,NaN,NaN,2023-05-04,2023-08-07,Clay,Flood,CAN,NaN,Mild,0716789850,Delayed harvest

In [15]:
crops.rename({'Cost of Production (KES)':"COP",'Crop Type': "CP"}, axis=1, inplace=True)
crops.head()

,Farmer Name,County,CP,COP,Season,Planted Area (Acres),Yield (Kg),Market Price (KES/Kg),Revenue (KES),COP,Profit (KES),Planting Date,Harvest Date,Soil Type,Irrigation Method,Fertilizer Used,Pest Control,Weather Impact,Farmer Contact,Notes
0,Farmer 1,Kiambu,Potatoes,Organic,Long Rains,15.14,1654.76,100.19,2510066.72,8977.19,2501089.53,2023-08-01,2023-11-02,Peaty,Drip,NaN,Organic,Mild,0731810617,High yield
1,Farmer 2,Meru,Coffee,Local,Short Rains,13.54,1957.61,168.63,4469713.42,47882.55,4421830.87,2023-02-25,2023-09-07,Silty,Sprinkler,Error,Organic,Mild,0773993471,NaN
2,Farmer 3,Nakuru,Sorghum,Error,Long Rains,19.33,4679.65,102.63,9283667.03,69370.32,9214296.71,2023-07-08,2023-12-28,Peaty,NaN,CAN,NaN,NaN,0778642041,Delayed harvest
3,Farmer 4,Eldoret,Potatoes,Organic,Short Rains,1.56,420.18,125.2,82066.20,43454.15,38612.05,2023-03-22,2024-01-08,NaN,NaN,UREA,Chemical,Mild,0758586340,NaN
4,Farmer 5,Machakos,Tomatoes,Hybrid,Short Rains,13.93,Error,199.42,NaN,69673.69,NaN,2023-03-01,2023-10-24,Clay,NaN,UREA,NaN,Severe,0770291817,NaN

In [16]:
crops.rename(columns={'Cost of Production (KES)':'COP','Crop Type': 'CP'})

,Farmer Name,County,CP,COP,Season,Planted Area (Acres),Yield (Kg),Market Price (KES/Kg),Revenue (KES),COP,Profit (KES),Planting Date,Harvest Date,Soil Type,Irrigation Method,Fertilizer Used,Pest Control,Weather Impact,Farmer Contact,Notes
0,Farmer 1,Kiambu,Potatoes,Organic,Long Rains,15.14,1654.76,100.19,2510066.72,8977.19,2501089.53,2023-08-01,2023-11-02,Peaty,Drip,NaN,Organic,Mild,0731810617,High yield
1,Farmer 2,Meru,Coffee,Local,Short Rains,13.54,1957.61,168.63,4469713.42,47882.55,4421830.87,2023-02-25,2023-09-07,Silty,Sprinkler,Error,Organic,Mild,0773993471,NaN
2,Farmer 3,Nakuru,Sorghum,Error,Long Rains,19.33,4679.65,102.63,9283667.03,69370.32,9214296.71,2023-07-08,2023-12-28,Peaty,NaN,CAN,NaN,NaN,0778642041,Delayed harvest
3,Farmer 4,Eldoret,Potatoes,Organic,Short Rains,1.56,420.18,125.2,82066.20,43454.15,38612.05,2023-03-22,2024-01-08,NaN,NaN,UREA,Chemical,Mild,0758586340,NaN
4,Farmer 5,Machakos,Tomatoes,Hybrid,Short Rains,13.93,Error,199.42,NaN,69673.69,NaN,2023-03-01,2023-10-24,Clay,NaN,UREA,NaN,Severe,0770291817,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Farmer 496,Eldoret,Potatoes,Hybrid,Dry Season,10.06,2023.1,50.35,1024742.64,27940.08,996802.56,2023-11-08,2023-04-07,NaN,Drip,DAP,NaN,Mild,0779008866,Delayed harvest
496,Farmer 497,Eldoret,Beans,Hybrid,Dry Season,19.4,3223.27,95.21,5953618.21,68258.75,5885359.46,2023-09-26,2023-09-11,Clay,Flood,NaN,Chemical,Severe,0768353204,Delayed harvest
497,Farmer 498,NaN,Beans,Organic,Dry Season,0.67,2133.31,155.02,221572.83,2280.99,219291.84,2023-11-26,2024-01-31,Loam,Flood,Manure,NaN,Mild,0718526544,NaN
498,Farmer 499,Kericho,Cassava,Hybrid,Dry Season,6.36,4112.78,Error,NaN,54915.02,NaN,2023-11-17,2023-09-24,Loam,Sprinkler,NaN,Chemical,Mild,0725014631,Pest issues
499,Farmer 500,Meru,Tea,Organic,Dry Season,10.74,Error,174.88,NaN,NaN,NaN,2023-05-04,2023-08-07,Clay,Flood,CAN,NaN,Mild,0716789850,Delayed harvest

In [17]:
crops.columns=crops.columns.str.lower()
crops

,farmer name,county,cp,cop,season,planted area (acres),yield (kg),market price (kes/kg),revenue (kes),cop,profit (kes),planting date,harvest date,soil type,irrigation method,fertilizer used,pest control,weather impact,farmer contact,notes
0,Farmer 1,Kiambu,Potatoes,Organic,Long Rains,15.14,1654.76,100.19,2510066.72,8977.19,2501089.53,2023-08-01,2023-11-02,Peaty,Drip,NaN,Organic,Mild,0731810617,High yield
1,Farmer 2,Meru,Coffee,Local,Short Rains,13.54,1957.61,168.63,4469713.42,47882.55,4421830.87,2023-02-25,2023-09-07,Silty,Sprinkler,Error,Organic,Mild,0773993471,NaN
2,Farmer 3,Nakuru,Sorghum,Error,Long Rains,19.33,4679.65,102.63,9283667.03,69370.32,9214296.71,2023-07-08,2023-12-28,Peaty,NaN,CAN,NaN,NaN,0778642041,Delayed harvest
3,Farmer 4,Eldoret,Potatoes,Organic,Short Rains,1.56,420.18,125.2,82066.20,43454.15,38612.05,2023-03-22,2024-01-08,NaN,NaN,UREA,Chemical,Mild,0758586340,NaN
4,Farmer 5,Machakos,Tomatoes,Hybrid,Short Rains,13.93,Error,199.42,NaN,69673.69,NaN,2023-03-01,2023-10-24,Clay,NaN,UREA,NaN,Severe,0770291817,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Farmer 496,Eldoret,Potatoes,Hybrid,Dry Season,10.06,2023.1,50.35,1024742.64,27940.08,996802.56,2023-11-08,2023-04-07,NaN,Drip,DAP,NaN,Mild,0779008866,Delayed harvest
496,Farmer 497,Eldoret,Beans,Hybrid,Dry Season,19.4,3223.27,95.21,5953618.21,68258.75,5885359.46,2023-09-26,2023-09-11,Clay,Flood,NaN,Chemical,Severe,0768353204,Delayed harvest
497,Farmer 498,NaN,Beans,Organic,Dry Season,0.67,2133.31,155.02,221572.83,2280.99,219291.84,2023-11-26,2024-01-31,Loam,Flood,Manure,NaN,Mild,0718526544,NaN
498,Farmer 499,Kericho,Cassava,Hybrid,Dry Season,6.36,4112.78,Error,NaN,54915.02,NaN,2023-11-17,2023-09-24,Loam,Sprinkler,NaN,Chemical,Mild,0725014631,Pest issues
499,Farmer 500,Meru,Tea,Organic,Dry Season,10.74,Error,174.88,NaN,NaN,NaN,2023-05-04,2023-08-07,Clay,Flood,CAN,NaN,Mild,0716789850,Delayed harvest

In [18]:
crops.columns=crops.columns.str.upper()
crops

,FARMER NAME,COUNTY,CP,COP,SEASON,PLANTED AREA (ACRES),YIELD (KG),MARKET PRICE (KES/KG),REVENUE (KES),COP,PROFIT (KES),PLANTING DATE,HARVEST DATE,SOIL TYPE,IRRIGATION METHOD,FERTILIZER USED,PEST CONTROL,WEATHER IMPACT,FARMER CONTACT,NOTES
0,Farmer 1,Kiambu,Potatoes,Organic,Long Rains,15.14,1654.76,100.19,2510066.72,8977.19,2501089.53,2023-08-01,2023-11-02,Peaty,Drip,NaN,Organic,Mild,0731810617,High yield
1,Farmer 2,Meru,Coffee,Local,Short Rains,13.54,1957.61,168.63,4469713.42,47882.55,4421830.87,2023-02-25,2023-09-07,Silty,Sprinkler,Error,Organic,Mild,0773993471,NaN
2,Farmer 3,Nakuru,Sorghum,Error,Long Rains,19.33,4679.65,102.63,9283667.03,69370.32,9214296.71,2023-07-08,2023-12-28,Peaty,NaN,CAN,NaN,NaN,0778642041,Delayed harvest
3,Farmer 4,Eldoret,Potatoes,Organic,Short Rains,1.56,420.18,125.2,82066.20,43454.15,38612.05,2023-03-22,2024-01-08,NaN,NaN,UREA,Chemical,Mild,0758586340,NaN
4,Farmer 5,Machakos,Tomatoes,Hybrid,Short Rains,13.93,Error,199.42,NaN,69673.69,NaN,2023-03-01,2023-10-24,Clay,NaN,UREA,NaN,Severe,0770291817,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Farmer 496,Eldoret,Potatoes,Hybrid,Dry Season,10.06,2023.1,50.35,1024742.64,27940.08,996802.56,2023-11-08,2023-04-07,NaN,Drip,DAP,NaN,Mild,0779008866,Delayed harvest
496,Farmer 497,Eldoret,Beans,Hybrid,Dry Season,19.4,3223.27,95.21,5953618.21,68258.75,5885359.46,2023-09-26,2023-09-11,Clay,Flood,NaN,Chemical,Severe,0768353204,Delayed harvest
497,Farmer 498,NaN,Beans,Organic,Dry Season,0.67,2133.31,155.02,221572.83,2280.99,219291.84,2023-11-26,2024-01-31,Loam,Flood,Manure,NaN,Mild,0718526544,NaN
498,Farmer 499,Kericho,Cassava,Hybrid,Dry Season,6.36,4112.78,Error,NaN,54915.02,NaN,2023-11-17,2023-09-24,Loam,Sprinkler,NaN,Chemical,Mild,0725014631,Pest issues
499,Farmer 500,Meru,Tea,Organic,Dry Season,10.74,Error,174.88,NaN,NaN,NaN,2023-05-04,2023-08-07,Clay,Flood,CAN,NaN,Mild,0716789850,Delayed harvest

In [19]:
crops.columns=crops.columns.str.replace(' ','_')
crops

,FARMER_NAME,COUNTY,CP,COP,SEASON,PLANTED_AREA_(ACRES),YIELD_(KG),MARKET_PRICE_(KES/KG),REVENUE_(KES),COP,PROFIT_(KES),PLANTING_DATE,HARVEST_DATE,SOIL_TYPE,IRRIGATION_METHOD,FERTILIZER_USED,PEST_CONTROL,WEATHER_IMPACT,FARMER_CONTACT,NOTES
0,Farmer 1,Kiambu,Potatoes,Organic,Long Rains,15.14,1654.76,100.19,2510066.72,8977.19,2501089.53,2023-08-01,2023-11-02,Peaty,Drip,NaN,Organic,Mild,0731810617,High yield
1,Farmer 2,Meru,Coffee,Local,Short Rains,13.54,1957.61,168.63,4469713.42,47882.55,4421830.87,2023-02-25,2023-09-07,Silty,Sprinkler,Error,Organic,Mild,0773993471,NaN
2,Farmer 3,Nakuru,Sorghum,Error,Long Rains,19.33,4679.65,102.63,9283667.03,69370.32,9214296.71,2023-07-08,2023-12-28,Peaty,NaN,CAN,NaN,NaN,0778642041,Delayed harvest
3,Farmer 4,Eldoret,Potatoes,Organic,Short Rains,1.56,420.18,125.2,82066.20,43454.15,38612.05,2023-03-22,2024-01-08,NaN,NaN,UREA,Chemical,Mild,0758586340,NaN
4,Farmer 5,Machakos,Tomatoes,Hybrid,Short Rains,13.93,Error,199.42,NaN,69673.69,NaN,2023-03-01,2023-10-24,Clay,NaN,UREA,NaN,Severe,0770291817,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Farmer 496,Eldoret,Potatoes,Hybrid,Dry Season,10.06,2023.1,50.35,1024742.64,27940.08,996802.56,2023-11-08,2023-04-07,NaN,Drip,DAP,NaN,Mild,0779008866,Delayed harvest
496,Farmer 497,Eldoret,Beans,Hybrid,Dry Season,19.4,3223.27,95.21,5953618.21,68258.75,5885359.46,2023-09-26,2023-09-11,Clay,Flood,NaN,Chemical,Severe,0768353204,Delayed harvest
497,Farmer 498,NaN,Beans,Organic,Dry Season,0.67,2133.31,155.02,221572.83,2280.99,219291.84,2023-11-26,2024-01-31,Loam,Flood,Manure,NaN,Mild,0718526544,NaN
498,Farmer 499,Kericho,Cassava,Hybrid,Dry Season,6.36,4112.78,Error,NaN,54915.02,NaN,2023-11-17,2023-09-24,Loam,Sprinkler,NaN,Chemical,Mild,0725014631,Pest issues
499,Farmer 500,Meru,Tea,Organic,Dry Season,10.74,Error,174.88,NaN,NaN,NaN,2023-05-04,2023-08-07,Clay,Flood,CAN,NaN,Mild,0716789850,Delayed harvest

In [20]:
crops.columns=crops.columns.str.replace(' ','_').str.lower()
crops

,farmer_name,county,cp,cop,season,planted_area_(acres),yield_(kg),market_price_(kes/kg),revenue_(kes),cop,profit_(kes),planting_date,harvest_date,soil_type,irrigation_method,fertilizer_used,pest_control,weather_impact,farmer_contact,notes
0,Farmer 1,Kiambu,Potatoes,Organic,Long Rains,15.14,1654.76,100.19,2510066.72,8977.19,2501089.53,2023-08-01,2023-11-02,Peaty,Drip,NaN,Organic,Mild,0731810617,High yield
1,Farmer 2,Meru,Coffee,Local,Short Rains,13.54,1957.61,168.63,4469713.42,47882.55,4421830.87,2023-02-25,2023-09-07,Silty,Sprinkler,Error,Organic,Mild,0773993471,NaN
2,Farmer 3,Nakuru,Sorghum,Error,Long Rains,19.33,4679.65,102.63,9283667.03,69370.32,9214296.71,2023-07-08,2023-12-28,Peaty,NaN,CAN,NaN,NaN,0778642041,Delayed harvest
3,Farmer 4,Eldoret,Potatoes,Organic,Short Rains,1.56,420.18,125.2,82066.20,43454.15,38612.05,2023-03-22,2024-01-08,NaN,NaN,UREA,Chemical,Mild,0758586340,NaN
4,Farmer 5,Machakos,Tomatoes,Hybrid,Short Rains,13.93,Error,199.42,NaN,69673.69,NaN,2023-03-01,2023-10-24,Clay,NaN,UREA,NaN,Severe,0770291817,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Farmer 496,Eldoret,Potatoes,Hybrid,Dry Season,10.06,2023.1,50.35,1024742.64,27940.08,996802.56,2023-11-08,2023-04-07,NaN,Drip,DAP,NaN,Mild,0779008866,Delayed harvest
496,Farmer 497,Eldoret,Beans,Hybrid,Dry Season,19.4,3223.27,95.21,5953618.21,68258.75,5885359.46,2023-09-26,2023-09-11,Clay,Flood,NaN,Chemical,Severe,0768353204,Delayed harvest
497,Farmer 498,NaN,Beans,Organic,Dry Season,0.67,2133.31,155.02,221572.83,2280.99,219291.84,2023-11-26,2024-01-31,Loam,Flood,Manure,NaN,Mild,0718526544,NaN
498,Farmer 499,Kericho,Cassava,Hybrid,Dry Season,6.36,4112.78,Error,NaN,54915.02,NaN,2023-11-17,2023-09-24,Loam,Sprinkler,NaN,Chemical,Mild,0725014631,Pest issues
499,Farmer 500,Meru,Tea,Organic,Dry Season,10.74,Error,174.88,NaN,NaN,NaN,2023-05-04,2023-08-07,Clay,Flood,CAN,NaN,Mild,0716789850,Delayed harvest

In [21]:
crops['Country'] = 'Kenya'
crops

,farmer_name,county,cp,cop,season,planted_area_(acres),yield_(kg),market_price_(kes/kg),revenue_(kes),cop,...,planting_date,harvest_date,soil_type,irrigation_method,fertilizer_used,pest_control,weather_impact,farmer_contact,notes,Country
0,Farmer 1,Kiambu,Potatoes,Organic,Long Rains,15.14,1654.76,100.19,2510066.72,8977.19,...,2023-08-01,2023-11-02,Peaty,Drip,NaN,Organic,Mild,0731810617,High yield,Kenya
1,Farmer 2,Meru,Coffee,Local,Short Rains,13.54,1957.61,168.63,4469713.42,47882.55,...,2023-02-25,2023-09-07,Silty,Sprinkler,Error,Organic,Mild,0773993471,NaN,Kenya
2,Farmer 3,Nakuru,Sorghum,Error,Long Rains,19.33,4679.65,102.63,9283667.03,69370.32,...,2023-07-08,2023-12-28,Peaty,NaN,CAN,NaN,NaN,0778642041,Delayed harvest,Kenya
3,Farmer 4,Eldoret,Potatoes,Organic,Short Rains,1.56,420.18,125.2,82066.20,43454.15,...,2023-03-22,2024-01-08,NaN,NaN,UREA,Chemical,Mild,0758586340,NaN,Kenya
4,Farmer 5,Machakos,Tomatoes,Hybrid,Short Rains,13.93,Error,199.42,NaN,69673.69,...,2023-03-01,2023-10-24,Clay,NaN,UREA,NaN,Severe,0770291817,NaN,Kenya
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Farmer 496,Eldoret,Potatoes,Hybrid,Dry Season,10.06,2023.1,50.35,1024742.64,27940.08,...,2023-11-08,2023-04-07,NaN,Drip,DAP,NaN,Mild,0779008866,Delayed harvest,Kenya
496,Farmer 497,Eldoret,Beans,Hybrid,Dry Season,19.4,3223.27,95.21,5953618.21,68258.75,...,2023-09-26,2023-09-11,Clay,Flood,NaN,Chemical,Severe,0768353204,Delayed harvest,Kenya
497,Farmer 498,NaN,Beans,Organic,Dry Season,0.67,2133.31,155.02,221572.83,2280.99,...,2023-11-26,2024-01-31,Loam,Flood,Manure,NaN,Mild,0718526544,NaN,Kenya
498,Farmer 499,Kericho,Cassava,Hybrid,Dry Season,6.36,4112.78,Error,NaN,54915.02,...,2023-11-17,2023-09-24,Loam,Sprinkler,NaN,Chemical,Mild,0725014631,Pest issues,Kenya
499,Farmer 500,Meru,Tea,Organic,Dry Season,10.74,Error,174.88,NaN,NaN,...,2023-05-04,2023-08-07,Clay,Flood,CAN,NaN,Mild,0716789850,Delayed harvest,Kenya

In [22]:
median_value = crops['profit_(kes)'].median()
median_value

1660568.6099999999

In [23]:
mode_value = crops['profit_(kes)'].mode()
mode_value

0        -38937.97
1        -36177.33
2        -34819.27
3        -23601.90
4        -21828.81
          ...
399    11559963.62
400    12150703.64
401    12325597.02
402    12964279.45
403    13226742.98
Name: profit_(kes), Length: 404, dtype: float64

In [24]:
mean_value = crops['profit_(kes)'].mean()
mean_value

np.float64(2714988.052029703)

In [25]:
crops['profit_(kes)'].fillna(mean_value, inplace=True)
crops.head()

/tmp/ipykernel_3602/2739329021.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  crops['profit_(kes)'].fillna(mean_value, inplace=True)

,farmer_name,county,cp,cop,season,planted_area_(acres),yield_(kg),market_price_(kes/kg),revenue_(kes),cop,...,planting_date,harvest_date,soil_type,irrigation_method,fertilizer_used,pest_control,weather_impact,farmer_contact,notes,Country
0,Farmer 1,Kiambu,Potatoes,Organic,Long Rains,15.14,1654.76,100.19,2510066.72,8977.19,...,2023-08-01,2023-11-02,Peaty,Drip,NaN,Organic,Mild,0731810617,High yield,Kenya
1,Farmer 2,Meru,Coffee,Local,Short Rains,13.54,1957.61,168.63,4469713.42,47882.55,...,2023-02-25,2023-09-07,Silty,Sprinkler,Error,Organic,Mild,0773993471,NaN,Kenya
2,Farmer 3,Nakuru,Sorghum,Error,Long Rains,19.33,4679.65,102.63,9283667.03,69370.32,...,2023-07-08,2023-12-28,Peaty,NaN,CAN,NaN,NaN,0778642041,Delayed harvest,Kenya
3,Farmer 4,Eldoret,Potatoes,Organic,Short Rains,1.56,420.18,125.2,82066.20,43454.15,...,2023-03-22,2024-01-08,NaN,NaN,UREA,Chemical,Mild,0758586340,NaN,Kenya
4,Farmer 5,Machakos,Tomatoes,Hybrid,Short Rains,13.93,Error,199.42,NaN,69673.69,...,2023-03-01,2023-10-24,Clay,NaN,UREA,NaN,Severe,0770291817,NaN,Kenya